CREATE TABLE IF NOT EXISTS regions (
    `list_id` INT,
    `list_region` VARCHAR(22) CHARACTER SET utf8
);
INSERT INTO regions VALUES
    (1,'Dar es Salaam'),
    (2,'Arusha'),
    (3,'Dodoma'),
    (4,'Mwanza'),
    (5,'Zanzibar Urban/West'),
    (6,'Rukwa'),
    (7,'Kilimanjaro'),
    (8,'Iringa'),
    (9,'Mara'),
    (10,'Ruvuma'),
    (11,'Katavi'),
    (12,'Singida'),
    (13,'Pemba South'),
    (14,'Morogoro'),
    (15,'Njombe'),
    (16,'Tanga'),
    (17,'Lindi'),
    (18,'Mtwara'),
    (19,'Shinyanga'),
    (20,'Kagera'),
    (21,'Manyara'),
    (22,'Tabora'),
    (23,'Pemba North'),
    (24,'Kigoma'),
    (25,'Pwani'),
    (26,'Geita'),
    (27,'Simiyu'),
    (28,'Zanzibar North'),
    (29,'Mbeya'),
    (30,'Zanzibar Central/South');
